version: '3.8'

services:
  nc_root_db:
    image: postgres:16.6
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\""]
      interval: 10s
      timeout: 2s
      retries: 10
    volumes:
      - nc_db_data:/var/lib/postgresql/data

  nocodb:
    image: nocodb/nocodb:latest
    restart: always
    depends_on:
      nc_root_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - NC_DB=${NC_DB}
    ports:
      - "9280:8080"
    volumes:
      - nc_data:/usr/app/data

volumes:
  nc_db_data:
  nc_data:
