version: '3.8'

services:
  noco_db:
    image: postgres:16.6
    env_file:
      - .env
    environment:
      POSTGRES_DB: "${NC_POSTGRES_DB}"
      POSTGRES_USER: "${NC_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${NC_POSTGRES_PASSWORD}"
    volumes:
      - nc_db:/var/lib/postgresql/data
    labels:
      - "coolify.managed=true"
      - "coolify.applicationId=${{coolify.applicationId}}"
      - "coolify.type=application"

  nocodb:
    image: nocodb/nocodb:latest
    depends_on:
      - noco_db
    env_file:
      - .env
    environment:
      NC_DB: "${NC_DB_URL}"
    volumes:
      - nc_data:/usr/app/data
    labels:
      - "coolify.managed=true"
      - "coolify.applicationId=${{coolify.applicationId}}"
      - "coolify.type=application"

volumes:
  nc_db:
  nc_data:
