version: '3.8'

services:
  nocodb:
    image: nocodb/nocodb:latest
    restart: always
    environment:
      NC_DB: "pg://${NOCODB_DB_USER}:${NOCODB_DB_PASSWORD}@root_db:5432/${NOCODB_DB_NAME}"
    depends_on:
      root_db:
        condition: service_healthy
    volumes:
      - nocodb_data:/usr/app/data

  root_db:
    image: postgres:16.6
    restart: always
    environment:
      POSTGRES_DB: ${NOCODB_DB_NAME}
      POSTGRES_USER: ${NOCODB_DB_USER}
      POSTGRES_PASSWORD: ${NOCODB_DB_PASSWORD}
    volumes:
      - nocodb_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $NOCODB_DB_USER -d $NOCODB_DB_NAME || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  nocodb_db_data:
  nocodb_data:
