version: '3.9'
services:
  nocodb_db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${NOCODB_DB_USER}
      - POSTGRES_PASSWORD=${NOCODB_DB_PASSWORD}
      - POSTGRES_DB=${NOCODB_DB_NAME}
    volumes:
      - nocodb_db_data:/var/lib/postgresql/data

  nocodb:
    image: nocodb/nocodb:latest
    restart: unless-stopped
    depends_on:
      - nocodb_db
    environment:
      - NC_DB=pg
      - NC_DB_HOST=nocodb_db
      - NC_DB_PORT=5432
      - NC_DB_USER=${NOCODB_DB_USER}
      - NC_DB_PASSWORD=${NOCODB_DB_PASSWORD}
      - NC_DB_NAME=${NOCODB_DB_NAME}
      - NC_PORT=8080
      - NC_AUTH_JWT_SECRET=${NOCODB_JWT_SECRET}
    labels:
      - traefik.enable=true
      - traefik.http.routers.nocodb.rule=Host(`${NOCODB_HOST}`)
      - traefik.http.routers.nocodb.entrypoints=websecure
      - traefik.http.routers.nocodb.tls=true
      - traefik.http.routers.nocodb.tls.certresolver=le
      - traefik.http.services.nocodb.loadbalancer.server.port=8080
volumes:
  nocodb_db_data:
